Feature: Extend rules to allow multiple words in class
FundingOptions/eslint-plugin-funding-options pull request #5
Opened 2020-10-14 09:29 UTC by thomasparsons

# Pull request checklist

- [x] The PR has a proper title. Use [Semantic Commit Messages](https://seesparkbox.com/foundry/semantic_commit_messages). (No more branch-name title please)
- [x] Make sure you are requesting the right branch.
- [x] Make sure this is ready to be merged into the relevant branch. Please don't create a PR and let it hang for a few days.
- [x] Ensure all tests are passing.

# PR type

- new feature

# Description

- Support multi word classnames such as `oneWord twoWord threeWord`
- ensure everything still works

2020-10-14 15:55 UTC, lwkchan commented on .github/PULL_REQUEST_TEMPLATE.md
> +# Pull request checklist
👍🏻

2020-10-14 16:29 UTC, Tg7z requested changes, later dismissed
Can we please have a test where the `__element` and or the `--modifier` are checked for casing too. If this checks that already

2020-10-15 09:44 UTC, thomasparsons commented
> Can we please have a test where the `__element` and or the `--modifier` are checked for casing too. If this checks that already

We don't currently have any BEM support in this rule, I think adding it is a good idea, but we need to scope/spec those rules out a little first

2020-10-15 10:25 UTC, thomasparsons commented
> > Can we please have a test where the `__element` and or the `--modifier` are checked for casing too. If this checks that already
> 
> We don't currently have any BEM support in this rule, I think adding it is a good idea, but we need to scope/spec those rules out a little first

https://app.clubhouse.io/fundingoptions/story/19878/eslint-rule-support-bem

2020-10-15 10:53 UTC, Tg7z approved these changes

2020-10-15 10:55 UTC, merged